### ISSUE TITLE
Password is not asked anymore

### ISSUE THREAD

**Issue by mf35** [fupdec/mediaChips#120]
**Describe the bug**
After last installation (0.10.5), the app is opening without asking for a password, even though it has always been set.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - App Version 0.10.5

**Additional context**
Removing and setting the password back doesn't do anything. The password is never asked anymore.

**Comment by fupdec** [comment]
I checked and you are correct. I will fix it soon.
