### ISSUE TITLE
Problems with Video Preview

### ISSUE THREAD

**Issue by guestqwerty** [fupdec/mediaChips#138]
when I select "on over -> video" in the section video preview, the program works as if the timeline was selected.
Only with the version 0.11.1

 - OS: Windows,
 - App Version 0.11.1

**Comment by fupdec** [comment]
I can't reproduce this bug.  everything works.  describe in detail your actions and also errors from the developer console, if any.

**Comment by guestqwerty** [comment]
Maybe I explained myself wrong,
With the new version v0.11.1, by setting "video" in the "on hover" parameter, the timelines are also generated with consequent consumption of CPU resources.
In the previous version V0.11.0 selecting "video" the timelines are not generated.

**Comment by mf35** [comment]
Same version here, and same option selected, but no timelines are generated in mine.
I'm on Windows 10 too.

So when you hover on any of your video cards, the app generates and diplay frames on your video cards' thumbnails ?

**Comment by guestqwerty** [comment]
When I select "video" the timelines are generated, but the application shows the frames. I also tried to select "on Hover -> none", no preview is shown, but the timelines are generated anyway.
I notice that the timelines are always generated regardless of what I select, reinstalling the application the problem remains.

**Comment by fupdec** [comment]
Now I understand what you meant. Yes, sometimes timeline generation starts even when it is disabled. But the timeline itself is not visible, and this option works properly.
I will fix this bug soon and release a new version with minor changes.
In addition, during development, I found a way to slightly improve the performance when creating frames for the timeline.

**Comment by fupdec** [comment]
I tried adding a little delay after each frame and the app freeze was reduced. At least on a mid-budget processor.

**Comment by guestqwerty** [comment]
thanks for your time, look forward to the new version, have a nice day
