### ISSUE TITLE
starting up

### ISSUE THREAD

**Issue by thecat18** [fupdec/mediaChips#140]
I have downloaded v0.11.2 and the program gets stuck on loading...

**Comment by fupdec** [comment]
What is your operating system?
Freezes on a stage with a small logo on a white background?

**Comment by thecat18** [comment]
Windows 10 home.  yes just that splash screen. version 0.11.1 is ok, opens fast.

**Comment by fupdec** [comment]
Are you running 0.11.2 with an empty database, or did you already have data in it?
Have you tried 0.11.2 portable version?

**Comment by fupdec** [comment]
This is rather unusual behavior. Usually, if errors occur, they occur after the main application window has been opened.

**Comment by thecat18** [comment]
ok i tried again after adding some info in the database & this time it opened. Also I was wondering if I pay for the full version what other features do I get?

**Comment by thecat18** [comment]
Thanks for your help.

**Comment by fupdec** [comment]
In the free version, the number of videos per page (and in the built-in player) is limited to 5. In the unlocked version, you will unlock all the videos on the page and in the player.

**Comment by o-data** [comment]
@fupdec is this limitation still true?

I'm using the beta version and the minimum display it 20. So I can't go to page 2 to view more after the 5th video. Or am I reading this wrong?

Thank you.
