### ISSUE TITLE
When typing in a tag, performer, or website, the typed text remains after the item is added

### ISSUE THREAD

**Issue by jack12j** [fupdec/mediaChips#79]
When typing in the name of a pornstar (for instance), after hitting enter or clicking the correct name, the typed text remains in the input box. In the image, I typed in "sophia leo" which was enough to find "Sophia Leone", and when I hit enter, she was added to the video, but the "sophia leo" I entered is still there. It would be nice if that text disappeared so I could continue entering names.

![image](https://user-images.githubusercontent.com/84143509/118722017-39d20a80-b7f1-11eb-97e3-14c5d5eb2e54.png)

**Comment by mf35** [comment]
Yes i also thought it would be a nice quality of life improvement :)
